version: 2
jobs:
  build:
    docker:
      - image: python:3.7.8
        environment:
          PRE_COMMIT_HOME: /root/cache/pre-commit
      - image: minio/minio:RELEASE.2020-07-31T03-39-05Z
        environment:
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          MINIO_REGION: us-east-1
        entrypoint: sh
        command: ['-c', 'mkdir -p /data/my-bucket && minio server /data']
      - image: redis:3.2.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements_test.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /root/cache/pip
            - /root/cache/pre-commit
            - ./cc-test-reporter
      - run:
          name: Install dependencies
          command: |
            pip install --cache-dir /root/cache/pip -r requirements_test.txt
            pre-commit install --install-hooks
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements_test.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /root/cache/pip
            - /root/cache/pre-commit
            - ./cc-test-reporter
      - run:
          name: Run linting
          command: pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            set -xu
            ./cc-test-reporter before-build
            ./test.sh
            coverage combine
            coverage xml
            ./cc-test-reporter after-build --exit-code $?
