version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.8
        environment:
          PRE_COMMIT_HOME: /home/circleci/cache/pre-commit
      - image: minio/minio:RELEASE.2021-11-24T23-19-33Z.hotfix.1d85a4563
        environment:
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          MINIO_REGION: us-east-1
        entrypoint: sh
        command: ['-c', 'mkdir -p /data1 && mkdir -p /data2 && mkdir -p /data3 && mkdir -p /data4 && minio server /data{1...4}']
      - image: redis:3.2.11
      - image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
        environment:
          xpack.security.enabled: false
          transport.host: localhost
          http.port: 9201
      - image: docker.elastic.co/apm/apm-server:8.2.3
        command: ["apm-server", "-e", "-E", "output.elasticsearch.hosts=[\"localhost:9201\"]", "-E", "apm-server.host=localhost:8201"]
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "requirements_test.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /home/circleci/cache/pip
            - /home/circleci/cache/pre-commit
            - ./cc-test-reporter
      - run:
          name: Install dependencies
          command: |
            pip install --cache-dir /home/circleci/cache/pip -r requirements_test.txt
            pre-commit install --install-hooks
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: v3-dependencies-{{ checksum "requirements_test.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /home/circleci/cache/pip
            - /home/circleci/cache/pre-commit
            - ./cc-test-reporter
      - run:
          name: Run linting
          command: pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            set -xu
            ./cc-test-reporter before-build
            ./test_app.sh
            coverage combine
            coverage xml
            ./cc-test-reporter after-build --exit-code $?
